version: "3"

services:
  postgres:
    image: postgres:13.2
    command: postgres -N 2000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - local
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.2
    command: sh -c "redis-server --requirepass password"
    networks:
      - local
    ports:
      - 6379:6379

  rabbitmq:
    image: hunglv46/rabbitmq-delayed-message-exchange:latest
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - local

  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - local
    ports:
      - 9200:9200

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: "redisinsight"
    ports:
      - "8001:8001"
    networks:
      - local
    depends_on:
      - redis

  adminer:
    image: adminer:4-standalone
    ports:
      - "8080:8080"
    container_name: "adminer"
    networks:
      - local

networks:
  local:
    driver: bridge
